version: '2'
services:
    tests:
        build:
            context: .
        network_mode: "host"
        cap_add:
            - SYS_PTRACE

    client:
        image: yandex/clickhouse-client
        network_mode: "host"
